[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "openfhe-rs"
authors = [{name = "Alexandra", email = "a.mirzuitova@fairmath.xyz"}]
dynamic = ["version", "description"]
